require: rubocop-rails

AllCops:
  Exclude:
  - "db/schema.rb"
  - "node_modules/**/*"

Rails:
  Enabled: true

Layout/LineLength:
  Description: Limit lines to 120 characters.
  Enabled: true
  Max: 120
  AllowURI: true
  URISchemes:
  - http
  - https
