AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Metrics/LineLength:
  Description: Limit lines to 110 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 110
  AllowURI: true
  URISchemes:
  - http
  - https

Style/FrozenStringLiteralComment:
  Enabled: false
